# Generated by Django 6.0.6 on 2026-06-07 22:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('contato', models.CharField(max_length=120)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa Parceira',
                'verbose_name_plural': 'Empresas Parceiras',
            },
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doador',
                'verbose_name_plural': 'Doadores',
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_doacao', models.DateField(default=django.utils.timezone.localdate)),
                ('local', models.CharField(default='Hemepar Curitiba', max_length=120)),
                ('volume_ml', models.PositiveIntegerField(default=450)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('validada', 'Validada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('validada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes_validadas', to=settings.AUTH_USER_MODEL)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='core.doador')),
            ],
            options={
                'verbose_name': 'Doacao',
                'verbose_name_plural': 'Doacoes',
                'ordering': ['-data_doacao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('minimo_doacoes_validadas', models.PositiveIntegerField(default=1, help_text='Quantidade minima de doacoes validadas para concessao.', validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='core.empresaparceira')),
            ],
            options={
                'verbose_name': 'Beneficio',
                'verbose_name_plural': 'Beneficios',
            },
        ),
        migrations.CreateModel(
            name='ResgateBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_concessao', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resgates', to='core.beneficio')),
                ('concedido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resgates_concedidos', to=settings.AUTH_USER_MODEL)),
                ('doacao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doacao')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resgates', to='core.doador')),
            ],
            options={
                'verbose_name': 'Resgate de Beneficio',
                'verbose_name_plural': 'Resgates de Beneficios',
                'ordering': ['-data_concessao'],
            },
        ),
    ]
