# Generated by Django 6.0.6 on 2026-06-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaparceira',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empresaparceira',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/'),
        ),
    ]
