# Generated by Django 6.0.6 on 2026-06-07 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresaparceira_descricao_empresaparceira_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='beneficios/'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='minimo_doacoes_validadas',
            field=models.PositiveIntegerField(default=1, help_text='Mantido para compatibilidade; a regra ativa considera 1 doacao validada.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
