# Generated by Django 6.0.6 on 2026-06-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_beneficio_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
    ]
