# Generated by Django 6.0.6 on 2026-06-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresaparceira_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='codigo_cupom',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
